module.exports = [
  { airportCode: 'ABR', cityName: 'Aberdeen, South Dakota' },
  { airportCode: 'ABI', cityName: 'Abilene, Texas' },
  { airportCode: 'CAK', cityName: 'Akron, Ohio' },
  { airportCode: 'ALS', cityName: 'Alamosa, Colorado' },
  { airportCode: 'ABY', cityName: 'Albany, Georgia' },
  { airportCode: 'ALB', cityName: 'Albany, New York' },
  { airportCode: 'ABQ', cityName: 'Albuquerque, New Mexico' },
  { airportCode: 'AEX', cityName: 'Alexandria, Louisiana' },
  { airportCode: 'ABE', cityName: 'Allentown, Pennsylvania' },
  { airportCode: 'AIA', cityName: 'Alliance, Nebraska' },
  { airportCode: 'APN', cityName: 'Alpena, Michigan' },
  { airportCode: 'AOO', cityName: 'Altoona, Pennsylvania' },
  { airportCode: 'AMA', cityName: 'Amarillo, Texas' },
  { airportCode: 'ANC', cityName: 'Anchorage, Alaska' },
  { airportCode: 'ATW', cityName: 'Appleton, Wisconsin' },
  { airportCode: 'AVL', cityName: 'Asheville, North Carolina' },
  { airportCode: 'ASE', cityName: 'Aspen, Colorado' },
  { airportCode: 'AHN', cityName: 'Athens, Georgia' },
  { airportCode: 'ATL', cityName: 'Atlanta, Georgia' },
  { airportCode: 'ACY', cityName: 'Atlantic City, New Jersey' },
  { airportCode: 'AGS', cityName: 'Augusta, Georgia' },
  { airportCode: 'AUG', cityName: 'Augusta, Maine' },
  { airportCode: 'AUS', cityName: 'Austin, Texas' },
  { airportCode: 'BFL', cityName: 'Bakersfield, California' },
  { airportCode: 'BWI', cityName: 'Baltimore, Maryland' },
  { airportCode: 'BGR', cityName: 'Bangor, Maine' },
  { airportCode: 'BHB', cityName: 'Bar Harbor, Maine' },
  { airportCode: 'BRW', cityName: 'Barrow, Alaska' },
  { airportCode: 'BTR', cityName: 'Baton Rouge, Louisiana' },
  { airportCode: 'BPT', cityName: 'Beaumont, Texas' },
  { airportCode: 'BKW', cityName: 'Beckley, West Virginia' },
  { airportCode: 'BED', cityName: 'Bedford, Massachusetts' },
  { airportCode: 'BLI', cityName: 'Bellingham, Washington' },
  { airportCode: 'BJI', cityName: 'Bemidji, Minnesota' },
  { airportCode: 'BET', cityName: 'Bethel, Alaska' },
  { airportCode: 'BTT', cityName: 'Bettles, Alaska' },
  { airportCode: 'BIL', cityName: 'Billings, Montana' },
  { airportCode: 'BGM', cityName: 'Binghamton, New York' },
  { airportCode: 'BHM', cityName: 'Birmingham, Alabama' },
  { airportCode: 'BIS', cityName: 'Bismarck, North Dakota' },
  { airportCode: 'BMI', cityName: 'Bloomington, Illinois' },
  { airportCode: 'BMG', cityName: 'Bloomington, Indiana' },
  { airportCode: 'BLF', cityName: 'Bluefield, West Virginia' },
  { airportCode: 'BOI', cityName: 'Boise, Idaho' },
  { airportCode: 'BOS', cityName: 'Boston, Massachusetts' },
  { airportCode: 'BZN', cityName: 'Bozeman, Montana' },
  { airportCode: 'BKX', cityName: 'Brookings, South Dakota' },
  { airportCode: 'BRO', cityName: 'Brownsville, Texas' },
  { airportCode: 'BQK', cityName: 'Brunswick, Georgia' },
  { airportCode: 'BUF', cityName: 'Buffalo, New York' },
  { airportCode: 'BUR', cityName: 'Burbank, California' },
  { airportCode: 'BRL', cityName: 'Burlington, Iowa' },
  { airportCode: 'BBF', cityName: 'Burlington, Massachusetts' },
  { airportCode: 'BTV', cityName: 'Burlington, Vermont' },
  { airportCode: 'BTM', cityName: 'Butte, Montana' },
  { airportCode: 'CGI', cityName: 'Cape Girardeau, Missouri' },
  { airportCode: 'CLD', cityName: 'Carlsbad, California' },
  { airportCode: 'CNM', cityName: 'Carlsbad, New Mexico' },
  { airportCode: 'CPR', cityName: 'Casper, Wyoming' },
  { airportCode: 'CID', cityName: 'Cedar Rapids, Iowa' },
  { airportCode: 'CMI', cityName: 'Champaign, Illinois' },
  { airportCode: 'CHS', cityName: 'Charleston, South Carolina' },
  { airportCode: 'CRW', cityName: 'Charleston, West Virginia' },
  { airportCode: 'CLT', cityName: 'Charlotte, North Carolina' },
  { airportCode: 'CHO', cityName: 'Charlottesville, Virginia' },
  { airportCode: 'CHA', cityName: 'Chattanooga, Tennessee' },
  { airportCode: 'CYS', cityName: 'Cheyenne, Wyoming' },
  { airportCode: 'CHI', cityName: 'Chicago, Illinois' },
  { airportCode: 'MDW', cityName: 'Chicago, Illinois' },
  { airportCode: 'CHI', cityName: 'Chicago, Illinois' },
  { airportCode: 'ORD', cityName: 'Chicago, Illinois' },
  { airportCode: 'CIC', cityName: 'Chico, California' },
  { airportCode: 'CVG', cityName: 'Cincinnati, Ohio' },
  { airportCode: 'CKB', cityName: 'Clarksburg, West Virginia' },
  { airportCode: 'CLE', cityName: 'Cleveland, Ohio' },
  { airportCode: 'CVN', cityName: 'Clovis, New Mexico' },
  { airportCode: 'COD', cityName: 'Cody, Wyoming' },
  { airportCode: 'CLL', cityName: 'College Station, Texas' },
  { airportCode: 'COS', cityName: 'Colorado Springs, Colorado' },
  { airportCode: 'COU', cityName: 'Columbia, Missouri' },
  { airportCode: 'CAE', cityName: 'Columbia, South Carolina' },
  { airportCode: 'CSG', cityName: 'Columbus, Georgia' },
  { airportCode: 'CLU', cityName: 'Columbus, Indiana' },
  { airportCode: 'GTR', cityName: 'Columbus, Mississippi' },
  { airportCode: 'OLU', cityName: 'Columbus, Nebraska' },
  { airportCode: 'CMH', cityName: 'Columbus, Ohio' },
  { airportCode: 'CDV', cityName: 'Cordova, Alaska' },
  { airportCode: 'CRP', cityName: 'Corpus Christi, Texas' },
  { airportCode: 'DAL', cityName: 'Dallas, Texas' },
  { airportCode: 'DFW', cityName: 'Dallas, Texas' },
  { airportCode: 'DAY', cityName: 'Dayton, Ohio' },
  { airportCode: 'DAB', cityName: 'Daytona Beach, Florida' },
  { airportCode: 'DEC', cityName: 'Decatur, Illinois' },
  { airportCode: 'DEN', cityName: 'Denver, Colorado' },
  { airportCode: 'DSM', cityName: 'Des Moines, Iowa' },
  { airportCode: 'DTW', cityName: 'Detroit, Michigan' },
  { airportCode: 'DTT', cityName: 'Detroit, Michigan' },
  { airportCode: 'DVL', cityName: 'Devils Lake, North Dakota' },
  { airportCode: 'DIK', cityName: 'Dickinson, North Dakota' },
  { airportCode: 'DLG', cityName: 'Dillingham, Alaska' },
  { airportCode: 'DDC', cityName: 'Dodge City, Kansas' },
  { airportCode: 'DHN', cityName: 'Dothan, Alabama' },
  { airportCode: 'DUJ', cityName: 'Du Bois, Pennsylvania' },
  { airportCode: 'DBQ', cityName: 'Dubuque, Iowa' },
  { airportCode: 'DLH', cityName: 'Duluth, Minnesota' },
  { airportCode: 'DRO', cityName: 'Durango, Colorado' },
  { airportCode: 'DUT', cityName: 'Dutch Harbor, Un Island, Alaska' },
  { airportCode: 'EAU', cityName: 'Eau Claire, Wisconsin' },
  { airportCode: 'EEK', cityName: 'Eek, Alaska' },
  { airportCode: 'IPL', cityName: 'El Centro, California' },
  { airportCode: 'ELD', cityName: 'El Dorado, Arkansas' },
  { airportCode: 'ELP', cityName: 'El Paso, Texas' },
  { airportCode: 'EKO', cityName: 'Elko, Nevada' },
  { airportCode: 'ELM', cityName: 'Elmira, New York' },
  { airportCode: 'WDG', cityName: 'Enid, Oklahoma' },
  { airportCode: 'ERI', cityName: 'Erie, Pennsylvania' },
  { airportCode: 'ESC', cityName: 'Escanaba, Michigan' },
  { airportCode: 'EUG', cityName: 'Eugene, Oregon' },
  { airportCode: 'ACV', cityName: 'Eureka, California' },
  { airportCode: 'EVV', cityName: 'Evansville, Indiana' },
  { airportCode: 'FAI', cityName: 'Fairbanks, Alaska' },
  { airportCode: 'FAR', cityName: 'Fargo, North Dakota' },
  { airportCode: 'FMN', cityName: 'Farmington, New Mexico' },
  { airportCode: 'XNA', cityName: 'Fayetteville, Arkansas' },
  { airportCode: 'FAY', cityName: 'Fayetteville, North Carolina' },
  { airportCode: 'FLG', cityName: 'Flagstaff, Arizona' },
  { airportCode: 'FNT', cityName: 'Flint, Michigan' },
  { airportCode: 'FLO', cityName: 'Florence, South Carolina' },
  { airportCode: 'FOD', cityName: 'Fort Dodge, Iowa' },
  { airportCode: 'FLL', cityName: 'Fort Lauderdale, Florida' },
  { airportCode: 'TBN', cityName: 'Fort Leonard Wood, Missouri' },
  { airportCode: 'RSW', cityName: 'Fort Myers, Florida' },
  { airportCode: 'FSM', cityName: 'Fort Smith, Arkansas' },
  { airportCode: 'VPS', cityName: 'Fort Walton Beach, Florida' },
  { airportCode: 'FWA', cityName: 'Fort Wayne, Indiana' },
  { airportCode: 'FYU', cityName: 'Fort Yukon, Alaska' },
  { airportCode: 'FAT', cityName: 'Fresno, California' },
  { airportCode: 'GNV', cityName: 'Gainesville, Florida' },
  { airportCode: 'GCK', cityName: 'Garden City, Kansas' },
  { airportCode: 'GCC', cityName: 'Gillette, Wyoming' },
  { airportCode: 'GDV', cityName: 'Glendive, Montana' },
  { airportCode: 'GFK', cityName: 'Grand Forks, North Dakota' },
  { airportCode: 'GRI', cityName: 'Grand Island, Nebraska' },
  { airportCode: 'GJT', cityName: 'Grand Junction, Colorado' },
  { airportCode: 'GRR', cityName: 'Grand Rapids, Michigan' },
  { airportCode: 'GBD', cityName: 'Great Bend, Kansas' },
  { airportCode: 'GTF', cityName: 'Great Falls, Montana' },
  { airportCode: 'GRB', cityName: 'Green Bay, Wisconsin' },
  { airportCode: 'LWB', cityName: 'Greenbrier, West Virginia' },
  { airportCode: 'GSO', cityName: 'Greensboro, North Carolina' },
  { airportCode: 'GLH', cityName: 'Greenville, Mississippi' },
  { airportCode: 'PGV', cityName: 'Greenville, North Carolina' },
  { airportCode: 'GSP', cityName: 'Greenville, South Carolina' },
  { airportCode: 'GPT', cityName: 'Gulfport, Mississippi' },
  { airportCode: 'GUC', cityName: 'Gunnison, Colorado' },
  { airportCode: 'HGR', cityName: 'Hagerstown, Maryland' },
  { airportCode: 'HNM', cityName: 'Hana, Maui, Hawaii' },
  { airportCode: 'CMX', cityName: 'Hancock, Michigan' },
  { airportCode: 'HRL', cityName: 'Harlingen, Texas' },
  { airportCode: 'MDT', cityName: 'Harrisburg, Pennsylvania' },
  { airportCode: 'HRO', cityName: 'Harrison, Arkansas' },
  { airportCode: 'BDL', cityName: 'Hartford, Connecticut' },
  { airportCode: 'HVR', cityName: 'Havre, Montana' },
  { airportCode: 'HYS', cityName: 'Hays, Kansas' },
  { airportCode: 'HLN', cityName: 'Helena, Montana' },
  { airportCode: 'HIB', cityName: 'Hibbing, Minnesota' },
  { airportCode: 'HHH', cityName: 'Hilton Head Island, South Carolina' },
  { airportCode: 'HOB', cityName: 'Hobbs, New Mexico' },
  { airportCode: 'HOM', cityName: 'Homer, Alaska' },
  { airportCode: 'HNL', cityName: 'Honolulu, Oahu, Hawaii' },
  { airportCode: 'MKK', cityName: 'Hoolehua, Molokai, Hawaii' },
  { airportCode: 'EFD', cityName: 'Houston, Texas' },
  { airportCode: 'HOU', cityName: 'Houston, Texas' },
  { airportCode: 'IAH', cityName: 'Houston, Texas' },
  { airportCode: 'EFD', cityName: 'Houston, Texas' },
  { airportCode: 'HTS', cityName: 'Huntington, West Virginia' },
  { airportCode: 'HSV', cityName: 'Huntsville, Alabama' },
  { airportCode: 'HON', cityName: 'Huron, South Dakota' },
  { airportCode: 'HYA', cityName: 'Hyannis, Massachusetts' },
  { airportCode: 'IDA', cityName: 'Idaho Falls, Idaho' },
  { airportCode: 'IND', cityName: 'Indianapolis, Indiana' },
  { airportCode: 'INL', cityName: 'International Falls, Minnesota' },
  { airportCode: 'IYK', cityName: 'Inyokern, California' },
  { airportCode: 'IMT', cityName: 'Iron Mountain, Michigan' },
  { airportCode: 'IWD', cityName: 'Ironwood, Michigan' },
  { airportCode: 'ISP', cityName: 'Islip, New York' },
  { airportCode: 'ITH', cityName: 'Ithaca, New York' },
  { airportCode: 'JAC', cityName: 'Jackson Hole, Wyoming' },
  { airportCode: 'JAN', cityName: 'Jackson, Mississippi' },
  { airportCode: 'MKL', cityName: 'Jackson, Tennessee' },
  { airportCode: 'JAX', cityName: 'Jacksonville, Florida' },
  { airportCode: 'OAJ', cityName: 'Jacksonville, North Carolina' },
  { airportCode: 'JMS', cityName: 'Jamestown, North Dakota' },
  { airportCode: 'JHW', cityName: 'Jamestown, New York' },
  { airportCode: 'JST', cityName: 'Johnstown, Pennsylvania' },
  { airportCode: 'JLN', cityName: 'Joplin, Missouri' },
  { airportCode: 'JNU', cityName: 'Juneau, Alaska' },
  { airportCode: 'OGG', cityName: 'Kahului, Maui, Hawaii' },
  { airportCode: 'AZO', cityName: 'Kalamazoo, Michigan' },
  { airportCode: 'LUP', cityName: 'Kalaupapa, Molokai, Hawaii' },
  { airportCode: 'FCA', cityName: 'Kalispell, Montana' },
  { airportCode: 'MCI', cityName: 'Kansas City, Missouri' },
  { airportCode: 'JHM', cityName: 'Kapalua, Maui, Hawaii' },
  { airportCode: 'EAR', cityName: 'Kearney, Nebraska' },
  { airportCode: 'ENA', cityName: 'Kenai, Alaska' },
  { airportCode: 'EYW', cityName: 'Key West, Florida' },
  { airportCode: 'GRK', cityName: 'Killeen, Texas' },
  { airportCode: 'AKN', cityName: 'King Salmon, Alaska' },
  { airportCode: 'IGM', cityName: 'Kingman, Arizona' },
  { airportCode: 'IRK', cityName: 'Kirksville, Missouri' },
  { airportCode: 'LMT', cityName: 'Klamath Falls, Oregon' },
  { airportCode: 'TYS', cityName: 'Knoxville, Tennessee' },
  { airportCode: 'ADQ', cityName: 'Kodiak, Alaska' },
  { airportCode: 'LSE', cityName: 'La Crosse, Wisconsin' },
  { airportCode: 'LFT', cityName: 'Lafayette, Louisiana' },
  { airportCode: 'LCH', cityName: 'Lake Charles, Louisiana' },
  { airportCode: 'LNY', cityName: 'Lanai City, Lanai, Hawaii' },
  { airportCode: 'LNS', cityName: 'Lancaster, Pennsylvania' },
  { airportCode: 'LAN', cityName: 'Lansing, Michigan' },
  { airportCode: 'LAR', cityName: 'Laramie, Wyoming' },
  { airportCode: 'LRD', cityName: 'Laredo, Texas' },
  { airportCode: 'LRU', cityName: 'Las Cruces, New Mexico' },
  { airportCode: 'LAS', cityName: 'Las Vegas, Nevada' },
  { airportCode: 'LBE', cityName: 'Latrobe, Pennsylvania' },
  { airportCode: 'PIB', cityName: 'Laurel, Mississippi' },
  { airportCode: 'LAW', cityName: 'Lawton, Oklahoma' },
  { airportCode: 'LWS', cityName: 'Lewiston, Idaho' },
  { airportCode: 'LEW', cityName: 'Lewiston, Maine' },
  { airportCode: 'LWT', cityName: 'Lewistown, Montana' },
  { airportCode: 'LEX', cityName: 'Lexington, Kentucky' },
  { airportCode: 'LBL', cityName: 'Liberal, Kansas' },
  { airportCode: 'LIH', cityName: 'Lihue, Kauai, Hawaii' },
  { airportCode: 'LNK', cityName: 'Lincoln, Nebraska' },
  { airportCode: 'LIT', cityName: 'Little Rock, Arkansas' },
  { airportCode: 'LGB', cityName: 'Long Beach, California' },
  { airportCode: 'GGG', cityName: 'Longview, Texas' },
  { airportCode: 'QLA', cityName: 'Los Angeles, California' },
  { airportCode: 'LBB', cityName: 'Lubbock, Texas' },
  { airportCode: 'LYH', cityName: 'Lynchburg, Virginia' },
  { airportCode: 'MCN', cityName: 'Macon, Georgia' },
  { airportCode: 'MSN', cityName: 'Madison, Wisconsin' },
  { airportCode: 'MHT', cityName: 'Manchester, New Hampshire' },
  { airportCode: 'MHK', cityName: 'Manhattan, Kansas' },
  { airportCode: 'MBL', cityName: 'Manistee, Michigan' },
  { airportCode: 'MWA', cityName: 'Marion, Illinois' },
  { airportCode: 'MQT', cityName: 'Marquette, Michigan' },
  { airportCode: 'MVY', cityName: 'Martha\'s Vineyard, Massachusetts' },
  { airportCode: 'MCW', cityName: 'Mason City, Iowa' },
  { airportCode: 'MSS', cityName: 'Massena, New York' },
  { airportCode: 'MFE', cityName: 'McAllen, Texas' },
  { airportCode: 'MCK', cityName: 'McCook, Nebraska' },
  { airportCode: 'MFR', cityName: 'Medford, Oregon' },
  { airportCode: 'MLB', cityName: 'Melbourne, Florida' },
  { airportCode: 'MEM', cityName: 'Memphis, Tennessee' },
  { airportCode: 'MEI', cityName: 'Meridian, Mississippi' },
  { airportCode: 'MIA', cityName: 'Miami, Florida' },
  { airportCode: 'MAF', cityName: 'Midland, Texas' },
  { airportCode: 'MLS', cityName: 'Miles City, Montana' },
  { airportCode: 'MKE', cityName: 'Milwaukee, Wisconsin' },
  { airportCode: 'MSP', cityName: 'Minneapolis, Minnesota' },
  { airportCode: 'MOT', cityName: 'Minot, North Dakota' },
  { airportCode: 'MSO', cityName: 'Missoula, Montana' },
  { airportCode: 'MOB', cityName: 'Mobile, Alabama' },
  { airportCode: 'MOD', cityName: 'Modesto, California' },
  { airportCode: 'MLI', cityName: 'Moline, Illinois' },
  { airportCode: 'MLU', cityName: 'Monroe, Louisiana' },
  { airportCode: 'MRY', cityName: 'Monterey, California' },
  { airportCode: 'MGM', cityName: 'Montgomery, Alabama' },
  { airportCode: 'MTJ', cityName: 'Montrose, Colorado' },
  { airportCode: 'MGW', cityName: 'Morgantown, West Virginia' },
  { airportCode: 'MWH', cityName: 'Moses Lake, Washington' },
  { airportCode: 'MSL', cityName: 'Muscle Shoals, Alabama' },
  { airportCode: 'MKG', cityName: 'Muskegon, Michigan' },
  { airportCode: 'MRY', cityName: 'Monterey, California' },
  { airportCode: 'ACK', cityName: 'Nantucket, Massachusetts' },
  { airportCode: 'BNA', cityName: 'Nashville, Tennessee' },
  { airportCode: 'EWN', cityName: 'New Bern, North Carolina' },
  { airportCode: 'HVN', cityName: 'New Haven, Connecticut' },
  { airportCode: 'MSY', cityName: 'New Orleans, Louisiana' },
  { airportCode: 'LGA', cityName: 'New York, New York' },
  { airportCode: 'JFK', cityName: 'New York, New York' },
  { airportCode: 'NYC', cityName: 'New York, New York' },
  { airportCode: 'EWR', cityName: 'Newark, New Jersey' },
  { airportCode: 'SWF', cityName: 'Newburgh, New York' },
  { airportCode: 'PHF', cityName: 'Newport News, Virginia' },
  { airportCode: 'OME', cityName: 'Nome, Alaska' },
  { airportCode: 'ORF', cityName: 'Norfolk, Virginia' },
  { airportCode: 'OTH', cityName: 'North Bend, Oregon' },
  { airportCode: 'LBF', cityName: 'North Platte, Nebraska' },
  { airportCode: 'OAK', cityName: 'Oakland, California' },
  { airportCode: 'OGS', cityName: 'Ogdensburg, New York' },
  { airportCode: 'OKC', cityName: 'Oklahoma City, Oklahoma' },
  { airportCode: 'OMA', cityName: 'Omaha, Nebraska' },
  { airportCode: 'ONT', cityName: 'Ontario, California' },
  { airportCode: 'SNA', cityName: 'Orange County, California' },
  { airportCode: 'MCO', cityName: 'Orlando, Florida' },
  { airportCode: 'OSH', cityName: 'Oshkosh, Wisconsin' },
  { airportCode: 'OWB', cityName: 'Owensboro, Kentucky' },
  { airportCode: 'OXR', cityName: 'Oxnard, California' },
  { airportCode: 'PAH', cityName: 'Paducah, Kentucky' },
  { airportCode: 'PGA', cityName: 'Page, Arizona' },
  { airportCode: 'PSP', cityName: 'Palm Springs, California' },
  { airportCode: 'PFN', cityName: 'Panama City, Florida' },
  { airportCode: 'PKB', cityName: 'Parkersburg, West Virginia' },
  { airportCode: 'PSC', cityName: 'Pasco, Washington' },
  { airportCode: 'PLN', cityName: 'Pellston, Michigan' },
  { airportCode: 'PDT', cityName: 'Pendleton, Oregon' },
  { airportCode: 'PNS', cityName: 'Pensacola, Florida' },
  { airportCode: 'PIA', cityName: 'Peoria, Illinois' },
  { airportCode: 'PHL', cityName: 'Philadelphia, Pennsylvania' },
  { airportCode: 'PHX', cityName: 'Phoenix, Arizona' },
  { airportCode: 'PIR', cityName: 'Pierre, South Dakota' },
  { airportCode: 'SOP', cityName: 'Pinehurst, North Carolina' },
  { airportCode: 'PIT', cityName: 'Pittsburgh, Pennsylvania' },
  { airportCode: 'PIH', cityName: 'Pocatello, Idaho' },
  { airportCode: 'PNC', cityName: 'Ponca City, Oklahoma' },
  { airportCode: 'PWM', cityName: 'Portland, Maine' },
  { airportCode: 'PDX', cityName: 'Portland, Oregon' },
  { airportCode: 'PSM', cityName: 'Portsmouth, New Hampshire' },
  { airportCode: 'PRC', cityName: 'Prescott, Arizona' },
  { airportCode: 'PQI', cityName: 'Presque Isle, Maine' },
  { airportCode: 'PVD', cityName: 'Providence, Rhode Island' },
  { airportCode: 'PVC', cityName: 'Provincetown, Massachusetts' },
  { airportCode: 'PUB', cityName: 'Pueblo, Colorado' },
  { airportCode: 'PUW', cityName: 'Pullman, Washington' },
  { airportCode: 'UIN', cityName: 'Quincy, Illinois' },
  { airportCode: 'RDU', cityName: 'Raleigh, North Carolina' },
  { airportCode: 'RAP', cityName: 'Rapid City, South Dakota' },
  { airportCode: 'RDD', cityName: 'Redding, California' },
  { airportCode: 'RDM', cityName: 'Redmond, Oregon' },
  { airportCode: 'RNO', cityName: 'Reno, Nevada' },
  { airportCode: 'RHI', cityName: 'Rhinelander, Wisconsin' },
  { airportCode: 'RIC', cityName: 'Richmond, Virginia' },
  { airportCode: 'RIW', cityName: 'Riverton, Wyoming' },
  { airportCode: 'ROA', cityName: 'Roanoke, Virginia' },
  { airportCode: 'RST', cityName: 'Rochester, Minnesota' },
  { airportCode: 'ROC', cityName: 'Rochester, New York' },
  { airportCode: 'RKS', cityName: 'Rock Springs, Wyoming' },
  { airportCode: 'RFD', cityName: 'Rockford, Illinois' },
  { airportCode: 'RKD', cityName: 'Rockland, Maine' },
  { airportCode: 'ROW', cityName: 'Roswell, New Mexico' },
  { airportCode: 'RUT', cityName: 'Rutland, Vermont' },
  { airportCode: 'SMF', cityName: 'Sacramento, California' },
  { airportCode: 'MBS', cityName: 'Saginaw, Michigan' },
  { airportCode: 'SLN', cityName: 'Salina, Kansas' },
  { airportCode: 'SLC', cityName: 'Salt Lake City, Utah' },
  { airportCode: 'SJT', cityName: 'San Angelo, Texas' },
  { airportCode: 'SAT', cityName: 'San Antonio, Texas' },
  { airportCode: 'SAN', cityName: 'San Diego, California' },
  { airportCode: 'QSF', cityName: 'San Francisco, California' },
  { airportCode: 'SFO', cityName: 'San Francisco, California' },
  { airportCode: 'SJC', cityName: 'San Jose, California' },
  { airportCode: 'SBP', cityName: 'San Luis Obispo, California' },
  { airportCode: 'SDP', cityName: 'Sand Point, Alaska' },
  { airportCode: 'SBA', cityName: 'Santa Barbara, California' },
  { airportCode: 'SAF', cityName: 'Santa Fe, New Mexico' },
  { airportCode: 'SMX', cityName: 'Santa Maria, California' },
  { airportCode: 'STS', cityName: 'Santa Rosa, California' },
  { airportCode: 'SLK', cityName: 'Saranac Lake, New York' },
  { airportCode: 'SRQ', cityName: 'Sarasota, Florida' },
  { airportCode: 'CIU', cityName: 'Sault Ste. Marie, Michigan' },
  { airportCode: 'SAV', cityName: 'Savannah, Georgia' },
  { airportCode: 'BFF', cityName: 'Scottsbluff, Nebraska' },
  { airportCode: 'SEA', cityName: 'Seattle, Washington' },
  { airportCode: 'SHD', cityName: 'Shenandoah Valley Airport, Virginia' },
  { airportCode: 'SHR', cityName: 'Sheridan, Wyoming' },
  { airportCode: 'SHV', cityName: 'Shreveport, Louisiana' },
  { airportCode: 'SDY', cityName: 'Sidney, Montana' },
  { airportCode: 'SVC', cityName: 'Silver City, New Mexico' },
  { airportCode: 'SUX', cityName: 'Sioux City, Iowa' },
  { airportCode: 'FSD', cityName: 'Sioux Falls, South Dakota' },
  { airportCode: 'SIT', cityName: 'Sitka, Alaska' },
  { airportCode: 'SGY', cityName: 'Skagway, Alaska' },
  { airportCode: 'SBN', cityName: 'South Bend, Indiana' },
  { airportCode: 'GEG', cityName: 'Spokane, Washington' },
  { airportCode: 'SPI', cityName: 'Springfield, Illinois' },
  { airportCode: 'CEF', cityName: 'Springfield, Massachusetts' },
  { airportCode: 'SGF', cityName: 'Springfield, Missouri' },
  { airportCode: 'VSF', cityName: 'Springfield, Vermont' },
  { airportCode: 'STC', cityName: 'St. Cloud, Minnesota' },
  { airportCode: 'SGU', cityName: 'St. George, Utah' },
  { airportCode: 'STL', cityName: 'St. Louis, Missouri' },
  { airportCode: 'PIE', cityName: 'St. Petersburg, Florida' },
  { airportCode: 'SCE', cityName: 'State College, Pennsylvania' },
  { airportCode: 'SBS', cityName: 'Steamboat Springs, Colorado' },
  { airportCode: 'SUN', cityName: 'Sun Valley, Idaho' },
  { airportCode: 'TLH', cityName: 'Tallahassee, Florida' },
  { airportCode: 'TPA', cityName: 'Tampa, Florida' },
  { airportCode: 'TXK', cityName: 'Texarkana, Arkansas' },
  { airportCode: 'TVF', cityName: 'Thief River Falls, Minnesota' },
  { airportCode: 'OOK', cityName: 'Toksook Bay, Alaska' },
  { airportCode: 'TOL', cityName: 'Toledo, Ohio' },
  { airportCode: 'TOP', cityName: 'Topeka, Kansas' },
  { airportCode: 'TVC', cityName: 'Traverse City, Michigan' },
  { airportCode: 'TTN', cityName: 'Trenton, New Jersey' },
  { airportCode: 'TUS', cityName: 'Tucson, Arizona' },
  { airportCode: 'TUL', cityName: 'Tulsa, Oklahoma' },
  { airportCode: 'TUP', cityName: 'Tupelo, Mississippi' },
  { airportCode: 'TWF', cityName: 'Twin Falls, Idaho' },
  { airportCode: 'TYR', cityName: 'Tyler, Texas' },
  { airportCode: 'UNK', cityName: 'Unalakleet, Alaska' },
  { airportCode: 'EGE', cityName: 'Vail, Colorado' },
  { airportCode: 'VDZ', cityName: 'Valdez, Alaska' },
  { airportCode: 'VLD', cityName: 'Valdosta, Georgia' },
  { airportCode: 'VCT', cityName: 'Victoria, Texas' },
  { airportCode: 'VIS', cityName: 'Visalia, California' },
  { airportCode: 'ACT', cityName: 'Waco, Texas' },
  { airportCode: 'ALW', cityName: 'Walla Walla, Washington' },
  { airportCode: 'ALO', cityName: 'Waterloo, Iowa' },
  { airportCode: 'ART', cityName: 'Watertown, New York' },
  { airportCode: 'ATY', cityName: 'Watertown, South Dakota' },
  { airportCode: 'CWA', cityName: 'Wausau, Wisconsin' },
  { airportCode: 'EAT', cityName: 'Wenatchee, Washington' },
  { airportCode: 'PBI', cityName: 'West Palm Beach, Florida' },
  { airportCode: 'WYS', cityName: 'West Yellowstone, Montana' },
  { airportCode: 'HPN', cityName: 'White Plains, New York' },
  { airportCode: 'SPS', cityName: 'Wichita Falls, Texas' },
  { airportCode: 'ICT', cityName: 'Wichita, Kansas' },
  { airportCode: 'AVP', cityName: 'Wilkes-Barre, Pennsylvania' },
  { airportCode: 'IPT', cityName: 'Williamsport, Pennsylvania' },
  { airportCode: 'ISN', cityName: 'Williston, North Dakota' },
  { airportCode: 'ILG', cityName: 'Wilmington, Delaware' },
  { airportCode: 'ILM', cityName: 'Wilmington, North Carolina' },
  { airportCode: 'OLF', cityName: 'Wolf Point, Montana' },
  { airportCode: 'WRL', cityName: 'Worland, Wyoming' },
  { airportCode: 'WRG', cityName: 'Wrangell, Alaska' },
  { airportCode: 'YKM', cityName: 'Yakima, Washington' },
  { airportCode: 'YAK', cityName: 'Yakutat, Alaska' },
  { airportCode: 'YUM', cityName: 'Yuma, Arizona' },
  { airportCode: 'LAX', cityName: 'Los Angeles, California' }
]
