module.exports = [
  { airportCode: 'ABR', cityName: 'Aberdeen, SD' },
  { airportCode: 'ABI', cityName: 'Abilene, TX' },
  { airportCode: 'CAK', cityName: 'Akron, OH' },
  { airportCode: 'ALS', cityName: 'Alamosa, CO' },
  { airportCode: 'ABY', cityName: 'Albany, GA' },
  { airportCode: 'ALB', cityName: 'Albany, NY' },
  { airportCode: 'ABQ', cityName: 'Albuquerque, NM' },
  { airportCode: 'AEX', cityName: 'Alexandria, LA' },
  { airportCode: 'ABE', cityName: 'Allentown, PA' },
  { airportCode: 'AIA', cityName: 'Alliance, NE' },
  { airportCode: 'APN', cityName: 'Alpena, MI' },
  { airportCode: 'AOO', cityName: 'Altoona, PA' },
  { airportCode: 'AMA', cityName: 'Amarillo, TX' },
  { airportCode: 'ANC', cityName: 'Anchorage, AK' },
  { airportCode: 'ATW', cityName: 'Appleton, WI' },
  { airportCode: 'AVL', cityName: 'Asheville, NC' },
  { airportCode: 'ASE', cityName: 'Aspen, CO' },
  { airportCode: 'AHN', cityName: 'Athens, GA' },
  { airportCode: 'ATL', cityName: 'Atlanta, GA' },
  { airportCode: 'ACY', cityName: 'Atlantic City, NJ' },
  { airportCode: 'AGS', cityName: 'Augusta, GA' },
  { airportCode: 'AUG', cityName: 'Augusta, ME' },
  { airportCode: 'AUS', cityName: 'Austin, TX' },
  { airportCode: 'BFL', cityName: 'Bakersfield, CA' },
  { airportCode: 'BWI', cityName: 'Baltimore, MD' },
  { airportCode: 'BGR', cityName: 'Bangor, ME' },
  { airportCode: 'BHB', cityName: 'Bar Harbor, ME' },
  { airportCode: 'BRW', cityName: 'Barrow, AK' },
  { airportCode: 'BTR', cityName: 'Baton Rouge, LA' },
  { airportCode: 'BPT', cityName: 'Beaumont, TX' },
  { airportCode: 'BKW', cityName: 'Beckley, WV' },
  { airportCode: 'BED', cityName: 'Bedford, MA' },
  { airportCode: 'BLI', cityName: 'Bellingham, WA' },
  { airportCode: 'BJI', cityName: 'Bemidji, MN' },
  { airportCode: 'BET', cityName: 'Bethel, AK' },
  { airportCode: 'BTT', cityName: 'Bettles, AK' },
  { airportCode: 'BIL', cityName: 'Billings, MT' },
  { airportCode: 'BGM', cityName: 'Binghamton, NY' },
  { airportCode: 'BHM', cityName: 'Birmingham, AL' },
  { airportCode: 'BIS', cityName: 'Bismarck, ND' },
  { airportCode: 'BMI', cityName: 'Bloomington, IL' },
  { airportCode: 'BMG', cityName: 'Bloomington, IN' },
  { airportCode: 'BLF', cityName: 'Bluefield, WV' },
  { airportCode: 'BOI', cityName: 'Boise, ID' },
  { airportCode: 'BOS', cityName: 'Boston, MA' },
  { airportCode: 'BZN', cityName: 'Bozeman, MT' },
  { airportCode: 'BKX', cityName: 'Brookings, SD' },
  { airportCode: 'BRO', cityName: 'Brownsville, TX' },
  { airportCode: 'BQK', cityName: 'Brunswick, GA' },
  { airportCode: 'BUF', cityName: 'Buffalo, NY' },
  { airportCode: 'BUR', cityName: 'Burbank, CA' },
  { airportCode: 'BRL', cityName: 'Burlington, IA' },
  { airportCode: 'BBF', cityName: 'Burlington, MA' },
  { airportCode: 'BTV', cityName: 'Burlington, VT' },
  { airportCode: 'BTM', cityName: 'Butte, MT' },
  { airportCode: 'CGI', cityName: 'Cape Girardeau, MO' },
  { airportCode: 'CLD', cityName: 'Carlsbad, CA' },
  { airportCode: 'CNM', cityName: 'Carlsbad, NM' },
  { airportCode: 'CPR', cityName: 'Casper, WY' },
  { airportCode: 'CID', cityName: 'Cedar Rapids, IA' },
  { airportCode: 'CMI', cityName: 'Champaign, IL' },
  { airportCode: 'CHS', cityName: 'Charleston, SC' },
  { airportCode: 'CRW', cityName: 'Charleston, WV' },
  { airportCode: 'CLT', cityName: 'Charlotte, NC' },
  { airportCode: 'CHO', cityName: 'Charlottesville, VA' },
  { airportCode: 'CHA', cityName: 'Chattanooga, TN' },
  { airportCode: 'CYS', cityName: 'Cheyenne, WY' },
  { airportCode: 'CHI', cityName: 'Chicago, IL' },
  { airportCode: 'MDW', cityName: 'Chicago, IL' },
  { airportCode: 'CHI', cityName: 'Chicago, IL' },
  { airportCode: 'ORD', cityName: 'Chicago, IL' },
  { airportCode: 'CIC', cityName: 'Chico, CA' },
  { airportCode: 'CVG', cityName: 'Cincinnati, OH' },
  { airportCode: 'CKB', cityName: 'Clarksburg, WV' },
  { airportCode: 'CLE', cityName: 'Cleveland, OH' },
  { airportCode: 'CVN', cityName: 'Clovis, NM' },
  { airportCode: 'COD', cityName: 'Cody, WY' },
  { airportCode: 'CLL', cityName: 'College Station, TX' },
  { airportCode: 'COS', cityName: 'Colorado Springs, CO' },
  { airportCode: 'COU', cityName: 'Columbia, MO' },
  { airportCode: 'CAE', cityName: 'Columbia, SC' },
  { airportCode: 'CSG', cityName: 'Columbus, GA' },
  { airportCode: 'CLU', cityName: 'Columbus, IN' },
  { airportCode: 'GTR', cityName: 'Columbus, MS' },
  { airportCode: 'OLU', cityName: 'Columbus, NE' },
  { airportCode: 'CMH', cityName: 'Columbus, OH' },
  { airportCode: 'CDV', cityName: 'Cordova, AK' },
  { airportCode: 'CRP', cityName: 'Corpus Christi, TX' },
  { airportCode: 'DAL', cityName: 'Dallas, TX' },
  { airportCode: 'DFW', cityName: 'Dallas, TX' },
  { airportCode: 'DAY', cityName: 'Dayton, OH' },
  { airportCode: 'DAB', cityName: 'Daytona Beach, FL' },
  { airportCode: 'DEC', cityName: 'Decatur, IL' },
  { airportCode: 'DEN', cityName: 'Denver, CO' },
  { airportCode: 'DSM', cityName: 'Des Moines, IA' },
  { airportCode: 'DTW', cityName: 'Detroit, MI' },
  { airportCode: 'DTT', cityName: 'Detroit, MI' },
  { airportCode: 'DVL', cityName: 'Devils Lake, ND' },
  { airportCode: 'DIK', cityName: 'Dickinson, ND' },
  { airportCode: 'DLG', cityName: 'Dillingham, AK' },
  { airportCode: 'DDC', cityName: 'Dodge City, KS' },
  { airportCode: 'DHN', cityName: 'Dothan, AL' },
  { airportCode: 'DUJ', cityName: 'Du Bois, PA' },
  { airportCode: 'DBQ', cityName: 'Dubuque, IA' },
  { airportCode: 'DLH', cityName: 'Duluth, MN' },
  { airportCode: 'DRO', cityName: 'Durango, CO' },
  { airportCode: 'DUT', cityName: 'Dutch Harbor, Un Island, AK' },
  { airportCode: 'EAU', cityName: 'Eau Claire, WI' },
  { airportCode: 'EEK', cityName: 'Eek, AK' },
  { airportCode: 'IPL', cityName: 'El Centro, CA' },
  { airportCode: 'ELD', cityName: 'El Dorado, AR' },
  { airportCode: 'ELP', cityName: 'El Paso, TX' },
  { airportCode: 'EKO', cityName: 'Elko, NV' },
  { airportCode: 'ELM', cityName: 'Elmira, NY' },
  { airportCode: 'WDG', cityName: 'Enid, OK' },
  { airportCode: 'ERI', cityName: 'Erie, PA' },
  { airportCode: 'ESC', cityName: 'Escanaba, MI' },
  { airportCode: 'EUG', cityName: 'Eugene, OR' },
  { airportCode: 'ACV', cityName: 'Eureka, CA' },
  { airportCode: 'EVV', cityName: 'Evansville, IN' },
  { airportCode: 'FAI', cityName: 'Fairbanks, AK' },
  { airportCode: 'FAR', cityName: 'Fargo, ND' },
  { airportCode: 'FMN', cityName: 'Farmington, NM' },
  { airportCode: 'XNA', cityName: 'Fayetteville, AR' },
  { airportCode: 'FAY', cityName: 'Fayetteville, NC' },
  { airportCode: 'FLG', cityName: 'Flagstaff, AZ' },
  { airportCode: 'FNT', cityName: 'Flint, MI' },
  { airportCode: 'FLO', cityName: 'Florence, SC' },
  { airportCode: 'FOD', cityName: 'Fort Dodge, IA' },
  { airportCode: 'FLL', cityName: 'Fort Lauderdale, FL' },
  { airportCode: 'TBN', cityName: 'Fort Leonard Wood, MO' },
  { airportCode: 'RSW', cityName: 'Fort Myers, FL' },
  { airportCode: 'FSM', cityName: 'Fort Smith, AR' },
  { airportCode: 'VPS', cityName: 'Fort Walton Beach, FL' },
  { airportCode: 'FWA', cityName: 'Fort Wayne, IN' },
  { airportCode: 'FYU', cityName: 'Fort Yukon, AK' },
  { airportCode: 'FAT', cityName: 'Fresno, CA' },
  { airportCode: 'GNV', cityName: 'Gainesville, FL' },
  { airportCode: 'GCK', cityName: 'Garden City, KS' },
  { airportCode: 'GCC', cityName: 'Gillette, WY' },
  { airportCode: 'GDV', cityName: 'Glendive, MT' },
  { airportCode: 'GFK', cityName: 'Grand Forks, ND' },
  { airportCode: 'GRI', cityName: 'Grand Island, NE' },
  { airportCode: 'GJT', cityName: 'Grand Junction, CO' },
  { airportCode: 'GRR', cityName: 'Grand Rapids, MI' },
  { airportCode: 'GBD', cityName: 'Great Bend, KS' },
  { airportCode: 'GTF', cityName: 'Great Falls, MT' },
  { airportCode: 'GRB', cityName: 'Green Bay, WI' },
  { airportCode: 'LWB', cityName: 'Greenbrier, WV' },
  { airportCode: 'GSO', cityName: 'Greensboro, NC' },
  { airportCode: 'GLH', cityName: 'Greenville, MS' },
  { airportCode: 'PGV', cityName: 'Greenville, NC' },
  { airportCode: 'GSP', cityName: 'Greenville, SC' },
  { airportCode: 'GPT', cityName: 'Gulfport, MS' },
  { airportCode: 'GUC', cityName: 'Gunnison, CO' },
  { airportCode: 'HGR', cityName: 'Hagerstown, MD' },
  { airportCode: 'HNM', cityName: 'Hana, Maui, HI' },
  { airportCode: 'CMX', cityName: 'Hancock, MI' },
  { airportCode: 'HRL', cityName: 'Harlingen, TX' },
  { airportCode: 'MDT', cityName: 'Harrisburg, PA' },
  { airportCode: 'HRO', cityName: 'Harrison, AR' },
  { airportCode: 'BDL', cityName: 'Hartford, CT' },
  { airportCode: 'HVR', cityName: 'Havre, MT' },
  { airportCode: 'HYS', cityName: 'Hays, KS' },
  { airportCode: 'HLN', cityName: 'Helena, MT' },
  { airportCode: 'HIB', cityName: 'Hibbing, MN' },
  { airportCode: 'Big', cityName: 'Kamuela, Hawaii' },
  { airportCode: 'HHH', cityName: 'Hilton Head Island, SC' },
  { airportCode: 'HOB', cityName: 'Hobbs, NM' },
  { airportCode: 'HOM', cityName: 'Homer, AK' },
  { airportCode: 'HNL', cityName: 'Honolulu, Oahu, HI' },
  { airportCode: 'MKK', cityName: 'Hoolehua, Molokai, HI' },
  { airportCode: 'EFD', cityName: 'Houston, TX' },
  { airportCode: 'HOU', cityName: 'Houston, TX' },
  { airportCode: 'IAH', cityName: 'Houston, TX' },
  { airportCode: 'EFD', cityName: 'Houston, TX' },
  { airportCode: 'HTS', cityName: 'Huntington, WV' },
  { airportCode: 'HSV', cityName: 'Huntsville, AL' },
  { airportCode: 'HON', cityName: 'Huron, SD' },
  { airportCode: 'HYA', cityName: 'Hyannis, MA' },
  { airportCode: 'IDA', cityName: 'Idaho Falls, ID' },
  { airportCode: 'IND', cityName: 'Indianapolis, IN' },
  { airportCode: 'INL', cityName: 'International Falls, MN' },
  { airportCode: 'IYK', cityName: 'Inyokern, CA' },
  { airportCode: 'IMT', cityName: 'Iron Mountain, MI' },
  { airportCode: 'IWD', cityName: 'Ironwood, MI' },
  { airportCode: 'ISP', cityName: 'Islip, NY' },
  { airportCode: 'ITH', cityName: 'Ithaca, NY' },
  { airportCode: 'JAC', cityName: 'Jackson Hole, WY' },
  { airportCode: 'JAN', cityName: 'Jackson, MS' },
  { airportCode: 'MKL', cityName: 'Jackson, TN' },
  { airportCode: 'JAX', cityName: 'Jacksonville, FL' },
  { airportCode: 'OAJ', cityName: 'Jacksonville, NC' },
  { airportCode: 'JMS', cityName: 'Jamestown, ND' },
  { airportCode: 'JHW', cityName: 'Jamestown, NY' },
  { airportCode: 'JST', cityName: 'Johnstown, PA' },
  { airportCode: 'JLN', cityName: 'Joplin, MO' },
  { airportCode: 'JNU', cityName: 'Juneau, AK' },
  { airportCode: 'OGG', cityName: 'Kahului, Maui, HI' },
  { airportCode: 'AZO', cityName: 'Kalamazoo, MI' },
  { airportCode: 'LUP', cityName: 'Kalaupapa, Molokai, HI' },
  { airportCode: 'FCA', cityName: 'Kalispell, MT' },
  { airportCode: 'MCI', cityName: 'Kansas City, MO' },
  { airportCode: 'JHM', cityName: 'Kapalua, Maui, HI' },
  { airportCode: 'EAR', cityName: 'Kearney, NE' },
  { airportCode: 'ENA', cityName: 'Kenai, AK' },
  { airportCode: 'KTM', cityName: 'Kathmandu' },
  { airportCode: 'EYW', cityName: 'Key West, FL' },
  { airportCode: 'GRK', cityName: 'Killeen, TX' },
  { airportCode: 'AKN', cityName: 'King Salmon, AK' },
  { airportCode: 'IGM', cityName: 'Kingman, AZ' },
  { airportCode: 'IRK', cityName: 'Kirksville, MO' },
  { airportCode: 'LMT', cityName: 'Klamath Falls, OR' },
  { airportCode: 'TYS', cityName: 'Knoxville, TN' },
  { airportCode: 'ADQ', cityName: 'Kodiak, AK' },
  { airportCode: 'LSE', cityName: 'La Crosse, WI' },
  { airportCode: 'LFT', cityName: 'Lafayette, LA' },
  { airportCode: 'LCH', cityName: 'Lake Charles, LA' },
  { airportCode: 'LNY', cityName: 'Lanai City, Lanai, HI' },
  { airportCode: 'LNS', cityName: 'Lancaster, PA' },
  { airportCode: 'LAN', cityName: 'Lansing, MI' },
  { airportCode: 'LAR', cityName: 'Laramie, WY' },
  { airportCode: 'LRD', cityName: 'Laredo, TX' },
  { airportCode: 'LRU', cityName: 'Las Cruces, NM' },
  { airportCode: 'LAS', cityName: 'Las Vegas, NV' },
  { airportCode: 'LBE', cityName: 'Latrobe, PA' },
  { airportCode: 'PIB', cityName: 'Laurel, MS' },
  { airportCode: 'LAW', cityName: 'Lawton, OK' },
  { airportCode: 'LWS', cityName: 'Lewiston, ID' },
  { airportCode: 'LEW', cityName: 'Lewiston, ME' },
  { airportCode: 'LWT', cityName: 'Lewistown, MT' },
  { airportCode: 'LEX', cityName: 'Lexington, KY' },
  { airportCode: 'LBL', cityName: 'Liberal, KS' },
  { airportCode: 'LIH', cityName: 'Lihue, Kauai, HI' },
  { airportCode: 'LNK', cityName: 'Lincoln, NE' },
  { airportCode: 'LIT', cityName: 'Little Rock, AR' },
  { airportCode: 'LGB', cityName: 'Long Beach, CA' },
  { airportCode: 'GGG', cityName: 'Longview, TX' },
  { airportCode: 'QLA', cityName: 'Los Angeles, CA' },
  { airportCode: 'SDF', cityName: 'Louisville, KY, USA' },
  { airportCode: 'LBB', cityName: 'Lubbock, TX' },
  { airportCode: 'LYH', cityName: 'Lynchburg, VA' },
  { airportCode: 'MCN', cityName: 'Macon, GA' },
  { airportCode: 'MSN', cityName: 'Madison, WI' },
  { airportCode: 'MHT', cityName: 'Manchester, NH' },
  { airportCode: 'MHK', cityName: 'Manhattan, KS' },
  { airportCode: 'MBL', cityName: 'Manistee, MI' },
  { airportCode: 'MWA', cityName: 'Marion, IL' },
  { airportCode: 'MQT', cityName: 'Marquette, MI' },
  { airportCode: 'MVY', cityName: 'Martha\'s Vineyard, MA' },
  { airportCode: 'MCW', cityName: 'Mason City, IA' },
  { airportCode: 'MSS', cityName: 'Massena, NY' },
  { airportCode: 'MFE', cityName: 'McAllen, TX' },
  { airportCode: 'MCK', cityName: 'McCook, NE' },
  { airportCode: 'MFR', cityName: 'Medford, OR' },
  { airportCode: 'MLB', cityName: 'Melbourne, FL' },
  { airportCode: 'MEM', cityName: 'Memphis, TN' },
  { airportCode: 'MEI', cityName: 'Meridian, MS' },
  { airportCode: 'MIA', cityName: 'Miami, FL' },
  { airportCode: 'MAF', cityName: 'Midland, TX' },
  { airportCode: 'MLS', cityName: 'Miles City, MT' },
  { airportCode: 'MKE', cityName: 'Milwaukee, WI' },
  { airportCode: 'MSP', cityName: 'Minneapolis, MN' },
  { airportCode: 'MOT', cityName: 'Minot, ND' },
  { airportCode: 'MSO', cityName: 'Missoula, MT' },
  { airportCode: 'MOB', cityName: 'Mobile, AL' },
  { airportCode: 'MOD', cityName: 'Modesto, CA' },
  { airportCode: 'MLI', cityName: 'Moline, IL' },
  { airportCode: 'MLU', cityName: 'Monroe, LA' },
  { airportCode: 'MRY', cityName: 'Monterey, CA' },
  { airportCode: 'MGM', cityName: 'Montgomery, AL' },
  { airportCode: 'MTJ', cityName: 'Montrose, CO' },
  { airportCode: 'MGW', cityName: 'Morgantown, WV' },
  { airportCode: 'MWH', cityName: 'Moses Lake, WA' },
  { airportCode: 'MSL', cityName: 'Muscle Shoals, AL' },
  { airportCode: 'MKG', cityName: 'Muskegon, MI' },
  { airportCode: 'MRY', cityName: 'Monterey, CA' },
  { airportCode: 'ACK', cityName: 'Nantucket, MA' },
  { airportCode: 'BNA', cityName: 'Nashville, TN' },
  { airportCode: 'EWN', cityName: 'New Bern, NC' },
  { airportCode: 'HVN', cityName: 'New Haven, CT' },
  { airportCode: 'MSY', cityName: 'New Orleans, LA' },
  { airportCode: 'LGA', cityName: 'New York, NY' },
  { airportCode: 'JFK', cityName: 'New York, NY' },
  { airportCode: 'NYC', cityName: 'New York, NY' },
  { airportCode: 'EWR', cityName: 'Newark, NJ' },
  { airportCode: 'SWF', cityName: 'Newburgh, NY' },
  { airportCode: 'PHF', cityName: 'Newport News, VA' },
  { airportCode: 'OME', cityName: 'Nome, AK' },
  { airportCode: 'ORF', cityName: 'Norfolk, VA' },
  { airportCode: 'OTH', cityName: 'North Bend, OR' },
  { airportCode: 'LBF', cityName: 'North Platte, NE' },
  { airportCode: 'OAK', cityName: 'Oakland, CA' },
  { airportCode: 'OGS', cityName: 'Ogdensburg, NY' },
  { airportCode: 'OKC', cityName: 'Oklahoma City, OK' },
  { airportCode: 'OMA', cityName: 'Omaha, NE' },
  { airportCode: 'ONT', cityName: 'Ontario, CA' },
  { airportCode: 'SNA', cityName: 'Orange County, CA' },
  { airportCode: 'MCO', cityName: 'Orlando, FL' },
  { airportCode: 'OSH', cityName: 'Oshkosh, WI' },
  { airportCode: 'OWB', cityName: 'Owensboro, KY' },
  { airportCode: 'OXR', cityName: 'Oxnard, CA' },
  { airportCode: 'PAH', cityName: 'Paducah, KY' },
  { airportCode: 'PGA', cityName: 'Page, AZ' },
  { airportCode: 'PSP', cityName: 'Palm Springs, CA' },
  { airportCode: 'PFN', cityName: 'Panama City, FL' },
  { airportCode: 'PKB', cityName: 'Parkersburg, WV' },
  { airportCode: 'PSC', cityName: 'Pasco, WA' },
  { airportCode: 'PLN', cityName: 'Pellston, MI' },
  { airportCode: 'PDT', cityName: 'Pendleton, OR' },
  { airportCode: 'PNS', cityName: 'Pensacola, FL' },
  { airportCode: 'PIA', cityName: 'Peoria, IL' },
  { airportCode: 'PHL', cityName: 'Philadelphia, PA' },
  { airportCode: 'PHX', cityName: 'Phoenix, AZ' },
  { airportCode: 'PIR', cityName: 'Pierre, SD' },
  { airportCode: 'SOP', cityName: 'Pinehurst, NC' },
  { airportCode: 'PIT', cityName: 'Pittsburgh, PA' },
  { airportCode: 'PIH', cityName: 'Pocatello, ID' },
  { airportCode: 'PNC', cityName: 'Ponca City, OK' },
  { airportCode: 'PWM', cityName: 'Portland, ME' },
  { airportCode: 'PDX', cityName: 'Portland, OR' },
  { airportCode: 'PSM', cityName: 'Portsmouth, NH' },
  { airportCode: 'PRC', cityName: 'Prescott, AZ' },
  { airportCode: 'PQI', cityName: 'Presque Isle, ME' },
  { airportCode: 'PVD', cityName: 'Providence, RI' },
  { airportCode: 'PVC', cityName: 'Provincetown, MA' },
  { airportCode: 'PUB', cityName: 'Pueblo, CO' },
  { airportCode: 'PUW', cityName: 'Pullman, WA' },
  { airportCode: 'UIN', cityName: 'Quincy, IL' },
  { airportCode: 'RDU', cityName: 'Raleigh, NC' },
  { airportCode: 'RAP', cityName: 'Rapid City, SD' },
  { airportCode: 'RDD', cityName: 'Redding, CA' },
  { airportCode: 'RDM', cityName: 'Redmond, OR' },
  { airportCode: 'RNO', cityName: 'Reno, NV' },
  { airportCode: 'RHI', cityName: 'Rhinelander, WI' },
  { airportCode: 'RIC', cityName: 'Richmond, VA' },
  { airportCode: 'RIW', cityName: 'Riverton, WY' },
  { airportCode: 'ROA', cityName: 'Roanoke, VA' },
  { airportCode: 'RST', cityName: 'Rochester, MN' },
  { airportCode: 'ROC', cityName: 'Rochester, NY' },
  { airportCode: 'RKS', cityName: 'Rock Springs, WY' },
  { airportCode: 'RFD', cityName: 'Rockford, IL' },
  { airportCode: 'RKD', cityName: 'Rockland, ME' },
  { airportCode: 'ROW', cityName: 'Roswell, NM' },
  { airportCode: 'RUT', cityName: 'Rutland, VT' },
  { airportCode: 'SMF', cityName: 'Sacramento, CA' },
  { airportCode: 'MBS', cityName: 'Saginaw, MI' },
  { airportCode: 'SLN', cityName: 'Salina, KS' },
  { airportCode: 'SLC', cityName: 'Salt Lake City, UT' },
  { airportCode: 'SJT', cityName: 'San Angelo, TX' },
  { airportCode: 'SAT', cityName: 'San Antonio, TX' },
  { airportCode: 'SAN', cityName: 'San Diego, CA' },
  { airportCode: 'QSF', cityName: 'San Francisco, CA' },
  { airportCode: 'SFO', cityName: 'San Francisco, CA' },
  { airportCode: 'SJC', cityName: 'San Jose, CA' },
  { airportCode: 'SBP', cityName: 'San Luis Obispo, CA' },
  { airportCode: 'SDP', cityName: 'Sand Point, AK' },
  { airportCode: 'SBA', cityName: 'Santa Barbara, CA' },
  { airportCode: 'SAF', cityName: 'Santa Fe, NM' },
  { airportCode: 'SMX', cityName: 'Santa Maria, CA' },
  { airportCode: 'STS', cityName: 'Santa Rosa, CA' },
  { airportCode: 'SLK', cityName: 'Saranac Lake, NY' },
  { airportCode: 'SRQ', cityName: 'Sarasota, FL' },
  { airportCode: 'CIU', cityName: 'Sault Ste. Marie, MI' },
  { airportCode: 'SAV', cityName: 'Savannah, GA' },
  { airportCode: 'BFF', cityName: 'Scottsbluff, NE' },
  { airportCode: 'SEA', cityName: 'Seattle, WA' },
  { airportCode: 'SHD', cityName: 'Shenandoah Valley Airport, VA' },
  { airportCode: 'SHR', cityName: 'Sheridan, WY' },
  { airportCode: 'SHV', cityName: 'Shreveport, LA' },
  { airportCode: 'SDY', cityName: 'Sidney, MT' },
  { airportCode: 'SVC', cityName: 'Silver City, NM' },
  { airportCode: 'SUX', cityName: 'Sioux City, IA' },
  { airportCode: 'FSD', cityName: 'Sioux Falls, SD' },
  { airportCode: 'SIT', cityName: 'Sitka, AK' },
  { airportCode: 'SGY', cityName: 'Skagway, AK' },
  { airportCode: 'SBN', cityName: 'South Bend, IN' },
  { airportCode: 'GEG', cityName: 'Spokane, WA' },
  { airportCode: 'SPI', cityName: 'Springfield, IL' },
  { airportCode: 'CEF', cityName: 'Springfield, MA' },
  { airportCode: 'SGF', cityName: 'Springfield, MO' },
  { airportCode: 'VSF', cityName: 'Springfield, VT' },
  { airportCode: 'STC', cityName: 'St. Cloud, MN' },
  { airportCode: 'SGU', cityName: 'St. George, UT' },
  { airportCode: 'STL', cityName: 'St. Louis, MO' },
  { airportCode: 'PIE', cityName: 'St. Petersburg, FL' },
  { airportCode: 'SCE', cityName: 'State College, PA' },
  { airportCode: 'SBS', cityName: 'Steamboat Springs, CO' },
  { airportCode: 'SUN', cityName: 'Sun Valley, ID' },
  { airportCode: 'TLH', cityName: 'Tallahassee, FL' },
  { airportCode: 'TPA', cityName: 'Tampa, FL' },
  { airportCode: 'TXK', cityName: 'Texarkana, AR' },
  { airportCode: 'TVF', cityName: 'Thief River Falls, MN' },
  { airportCode: 'OOK', cityName: 'Toksook Bay, AK' },
  { airportCode: 'TOL', cityName: 'Toledo, OH' },
  { airportCode: 'TOP', cityName: 'Topeka, KS' },
  { airportCode: 'TVC', cityName: 'Traverse City, MI' },
  { airportCode: 'TTN', cityName: 'Trenton, NJ' },
  { airportCode: 'TUS', cityName: 'Tucson, AZ' },
  { airportCode: 'TUL', cityName: 'Tulsa, OK' },
  { airportCode: 'TUP', cityName: 'Tupelo, MS' },
  { airportCode: 'TWF', cityName: 'Twin Falls, ID' },
  { airportCode: 'TYR', cityName: 'Tyler, TX' },
  { airportCode: 'UNK', cityName: 'Unalakleet, AK' },
  { airportCode: 'EGE', cityName: 'Vail, CO' },
  { airportCode: 'VDZ', cityName: 'Valdez, AK' },
  { airportCode: 'VLD', cityName: 'Valdosta, GA' },
  { airportCode: 'VCT', cityName: 'Victoria, TX' },
  { airportCode: 'VIS', cityName: 'Visalia, CA' },
  { airportCode: 'ACT', cityName: 'Waco, TX' },
  { airportCode: 'ALW', cityName: 'Walla Walla, WA' },
  { airportCode: 'DCA', cityName: 'Washington DC' },
  { airportCode: 'WAS', cityName: 'Washington DC' },
  { airportCode: 'IAD', cityName: 'Washington DC' },
  { airportCode: 'ALO', cityName: 'Waterloo, IA' },
  { airportCode: 'ART', cityName: 'Watertown, NY' },
  { airportCode: 'ATY', cityName: 'Watertown, SD' },
  { airportCode: 'CWA', cityName: 'Wausau, WI' },
  { airportCode: 'EAT', cityName: 'Wenatchee, WA' },
  { airportCode: 'PBI', cityName: 'West Palm Beach, FL' },
  { airportCode: 'WYS', cityName: 'West Yellowstone, MT' },
  { airportCode: 'HPN', cityName: 'White Plains, NY' },
  { airportCode: 'SPS', cityName: 'Wichita Falls, TX' },
  { airportCode: 'ICT', cityName: 'Wichita, KS' },
  { airportCode: 'AVP', cityName: 'Wilkes-Barre, PA' },
  { airportCode: 'IPT', cityName: 'Williamsport, PA' },
  { airportCode: 'ISN', cityName: 'Williston, ND' },
  { airportCode: 'ILG', cityName: 'Wilmington, DE' },
  { airportCode: 'ILM', cityName: 'Wilmington, NC' },
  { airportCode: 'OLF', cityName: 'Wolf Point, MT' },
  { airportCode: 'WRL', cityName: 'Worland, WY' },
  { airportCode: 'WRG', cityName: 'Wrangell, AK' },
  { airportCode: 'YKM', cityName: 'Yakima, WA' },
  { airportCode: 'YAK', cityName: 'Yakutat, AK' },
  { airportCode: 'YUM', cityName: 'Yuma, AZ' },
  { airportCode: 'YXX', cityName: 'Abbotsford, BC' },
  { airportCode: 'YAA', cityName: 'Anahim Lake, BC' },
  { airportCode: 'YEK', cityName: 'Arviat, NWT' },
  { airportCode: 'YBG', cityName: 'Bagotville, PQ' },
  { airportCode: 'YYC', cityName: 'Calgary, AB' },
  { airportCode: 'YBL', cityName: 'Campbell River, BC' },
  { airportCode: 'YGR', cityName: 'Cap-aux-Meules, Magdalens Islands, PQ' },
  { airportCode: 'YCG', cityName: 'Castlegar, BC' },
  { airportCode: 'YYG', cityName: 'Charlottetown, PEI' },
  { airportCode: 'YMT', cityName: 'Chibougamau, PQ' },
  { airportCode: 'YYQ', cityName: 'Churchill, MB' },
  { airportCode: 'YXC', cityName: 'Cranbrook, BC' },
  { airportCode: 'YDF', cityName: 'Deer Lake, NF' },
  { airportCode: 'YHD', cityName: 'Dryden, ON' },
  { airportCode: 'YEG', cityName: 'Edmonton, AB' },
  { airportCode: 'YMM', cityName: 'Fort McMurray, AB' },
  { airportCode: 'YYE', cityName: 'Fort Nelson, BC' },
  { airportCode: 'YXJ', cityName: 'Fort Saint John, BC' },
  { airportCode: 'YSM', cityName: 'Fort Smith, NWT' },
  { airportCode: 'YFC', cityName: 'Fredericton, NB' },
  { airportCode: 'YQX', cityName: 'Gander, NF' },
  { airportCode: 'YGP', cityName: 'Gaspe, PQ' },
  { airportCode: 'YQU', cityName: 'Grande Prairie, AB' },
  { airportCode: 'YHZ', cityName: 'Halifax, NS' },
  { airportCode: 'YHM', cityName: 'Hamilton, ON' },
  { airportCode: 'YFB', cityName: 'Iqaluit, Nunavut' },
  { airportCode: 'YKA', cityName: 'Kamloops, BC' },
  { airportCode: 'YLW', cityName: 'Kelowna, BC' },
  { airportCode: 'YQK', cityName: 'Kenora, ON' },
  { airportCode: 'YGK', cityName: 'Kingston, ON' },
  { airportCode: 'YQL', cityName: 'Lethbridge, AB' },
  { airportCode: 'YXU', cityName: 'London, ON' },
  { airportCode: 'YXH', cityName: 'Medicine Hat, AB' },
  { airportCode: 'YQM', cityName: 'Moncton, NB' },
  { airportCode: 'YYY', cityName: 'Mont-Joli, PQ' },
  { airportCode: 'YMQ', cityName: 'Montreal, PQ' },
  { airportCode: 'YUL', cityName: 'Montreal, PQ' },
  { airportCode: 'YCD', cityName: 'Nanaimo, BC' },
  { airportCode: 'YYB', cityName: 'North Bay, ON' },
  { airportCode: 'YOW', cityName: 'Ottawa, ON' },
  { airportCode: 'YYF', cityName: 'Penticton, BC' },
  { airportCode: 'YZT', cityName: 'Port Hardy, BC' },
  { airportCode: 'YPW', cityName: 'Powell River, BC' },
  { airportCode: 'YPR', cityName: 'Prince Rupert, BC' },
  { airportCode: 'YQB', cityName: 'Quebec, PQ' },
  { airportCode: 'YQZ', cityName: 'Quesnel, BC' },
  { airportCode: 'YRT', cityName: 'Rankin Inlet, NWT' },
  { airportCode: 'YRL', cityName: 'Red Lake, ON' },
  { airportCode: 'YQR', cityName: 'Regina, SK' },
  { airportCode: 'YRJ', cityName: 'Roberval, PQ' },
  { airportCode: 'YUY', cityName: 'Rouyn-Noranda, PQ' },
  { airportCode: 'YSJ', cityName: 'Saint John, NB' },
  { airportCode: 'YZP', cityName: 'Sandspit, Queen Charlotte Islands, BC' },
  { airportCode: 'YZR', cityName: 'Sarnia, ON' },
  { airportCode: 'YXE', cityName: 'Saskatoon, SK' },
  { airportCode: 'YAM', cityName: 'Sault Ste. Marie, ON' },
  { airportCode: 'YZV', cityName: 'Sept-Iles, PQ' },
  { airportCode: 'YXL', cityName: 'Sioux Lookout, ON' },
  { airportCode: 'YYD', cityName: 'Smithers, BC' },
  { airportCode: 'YYT', cityName: 'St. John\'s, NF' },
  { airportCode: 'YSB', cityName: 'Sudbury, ON' },
  { airportCode: 'YQY', cityName: 'Sydney, Cape Breton Island, NS' },
  { airportCode: 'YXT', cityName: 'Terrace, BC' },
  { airportCode: 'YTH', cityName: 'Thompson, MB' },
  { airportCode: 'YQT', cityName: 'Thunder Bay, ON' },
  { airportCode: 'YTS', cityName: 'Timmins, ON' },
  { airportCode: 'YYZ', cityName: 'Toronto, ON' },
  { airportCode: 'YTO', cityName: 'Toronto, ON' },
  { airportCode: 'YTZ', cityName: 'Toronto, ON' },
  { airportCode: 'YVO', cityName: 'Val-d\'Or, PQ' },
  { airportCode: 'YVR', cityName: 'Vancouver, BC' },
  { airportCode: 'YYJ', cityName: 'Victoria, BC' },
  { airportCode: 'YWK', cityName: 'Wabush, Labrador, NF' },
  { airportCode: 'YXY', cityName: 'Whitehorse, YT' },
  { airportCode: 'YWL', cityName: 'Williams Lake, BC' },
  { airportCode: 'YQG', cityName: 'Windsor, ON' },
  { airportCode: 'YWG', cityName: 'Winnipeg, MB' },
  { airportCode: 'YZF', cityName: 'Yellowknife, NWT' },
  { airportCode: 'LAX', cityName: 'Los Angeles, CA' }
];
